# vars_prompt:
#   name: 'server'
#   prompt: "Is this execution targeting a production server?"
#   default: no

- name: Update Packages
  dnf:
    name: "*"
    state: latest

- name: Upgrade Packages
  dnf:
    state: "latest"

- name: Install Essential Packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Start Crontab
  ansible.builtin.service:
    name: crond
    state: started

- name: Enable Crontab On Startup
  ansible.builtin.service:
    name: crond
    enabled: yes
# - name: Update Packages (Debian Based)
#   apt:
#     update_cache: yes
#     upgrade: yes
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
